Mobile first portfolio pull request
AbdusSattar-70/my-portfolio pull request #3
Opened 2023-01-13 13:30 UTC by AbdusSattar-70

Added toolbar and headline section from development branch to master.

2023-01-13 13:58 UTC, NduatiKagiri requested changes
Hi @AbdusSattar-70 ,

# CHANGES REQUIRED ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/87394385/212334637-bc886c63-7653-40a8-9eaf-78c6b898a861.gif)

## Highlights ✔️
✅ GitHub Flow observed
✅ Linters checks are passing
✅ Good documentation

## Required Changes ♻️

- [ ] You have not applied the sizes, padding, and margins from the Figma design.
-   Your design:
     ![johndoe1](https://user-images.githubusercontent.com/87394385/212335735-6c766cd7-9fba-4c7d-9e3f-a1f75dc46530.JPG)

-   Required Figma design:
    ![johndoe2](https://user-images.githubusercontent.com/87394385/212335930-4b6c9ea3-1b25-4dbd-91cd-3ce7377b9c10.JPG)

-   Kindly make sure that you remove the white spaces surrounding your design.
-   Make sure that your header occupies the whole width.
-    Please apply the right fonts for all the texts, and the right sizes for all the texts and images, as from the Figma design.
-    Kindly also remember to apply the right alignment of your content (that is center, right, left, bottom, end, top, and start), and also apply the right paddings and margins on all your elements. 


- [x] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 13:58 UTC, NduatiKagiri commented on index.html
> +        <h1>John Doe</h1>
- [ ] The page title/logo should be a link and not a heading. Please make this change.

2023-01-13 13:58 UTC, NduatiKagiri commented on index.html
> +  </div>
- [ ] You have done a great job on this headline section, apart from this image which you added as an image but should be added as a background image.

2023-01-20 17:32 UTC, AbdusSattar-70 reviewed
#4  please make sure

2023-01-20 17:32 UTC, AbdusSattar-70 commented on README.md
> +  <ul>
@AbdusSattar-70  problem is here.
![repository-open-graph-template](https://user-images.githubusercontent.com/118761303/213764087-034a6ad4-c3fa-4715-aa2d-7ee5ddf88199.png)

2023-01-20 17:32 UTC, AbdusSattar-70 commented on src/html/index.html
> +              </a>
> `_****_`
```suggestion
                <img src="media/icons/twitter.svg" alt="twitter icon" />
              </a>
            </li>
            <li>
              <a href="">
                <img src="media/icons/medium.png" alt="medium icon" />
              </a> [optional] you should try another one.
```

2023-01-20 17:32 UTC, AbdusSattar-70 commented on src/html/nav-mobile.html
> +      </nav>
#problem

2023-01-24 17:13 UTC, closed without merging